eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8989

info:
  app:
    description: The Gateway API for all three services
    endpoints:
    - http://localhost:8989/api/products
    - http://localhost:8989/api/orders
    - http://localhost:8989/api/invoices


spring:
  application:
    name: gateway-service    
  cloud:
    gateway:      
      routes:
      - id: product-service
        uri: lb://PRODUCT-SERVICE
        predicates:
         Path=/api/products/**
        filters:
        - RewritePath=/api/products(?<segment>/?.*), /products$\{segment}
         

      - id: orderprocessing-service
        uri: lb://ORDERPROCESSING-SERVICE
        predicates:
        - Path=/api/orders/**
        filters:
        - RewritePath=/api/orders(?<segment>/?.*), /orders$\{segment}
            
      - id: invoice-service
        uri: lb://invoice-service
        predicates:
        - Path=/api/invoices/**    
        filters:
        - RewritePath=/api/invoices(?<segment>/?.*), /invoices$\{segment}
  
logging:
  level:
    reactor:
      netty: INFO
    org:
       springframework:
          cloud:
            gateway: TRACE